"""Constants for the Audi connect integration."""

DOMAIN = "audiconnect"
CONF_COUNTRY = "region"
CONF_LEVEL = "level"
CONF_VIN = "vin"
CONF_ACTION = "action"
COUNTRY_CODE = {
    "AL": "Albania",
    "AM": "Armenia",
    "AU": "Australia",
    "AT": "Austria",
    "AZ": "Azerbaijan",
    "BE": "Belgium",
    "US": "United States",
    "BG": "Bulgaria",
    "CA": "Canada",
    "IC": "Canary Islands",
    "HR": "Croatia",
    "CY": "Cyprus",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "EE": "Estonia",
    "FI": "Finland",
    "FR": "France",
    "GE": "Georgia",
    "DE": "Germany",
    "GR": "Greece",
    "GL": "Greenland",
    "HK": "Hong Kong",
    "HU": "Hungary",
    "IS": "Iceland",
    "IE": "Ireland",
    "IT": "Italy",
    "JP": "Japan",
    "KR": "Korea (the Republic of)",
    "LV": "Latvia",
    "LI": "Liechtenstein",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "MY": "Malaysia",
    "MT": "Malta",
    "MX": "Mexico",
    "ME": "Montenegro",
    "NL": "Netherlands",
    "NZ": "New Zealand",
    "MK": "North Macedonia",
    "NO": "Norway",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "RS": "Serbia",
    "SG": "Singapore",
    "SK": "Slovakia",
    "SI": "Slovenia",
    "ES": "Spain",
    "SE": "Sweden",
    "CH": "Switzerland",
    "TW": "Taiwan",
    "UA": "Ukraine",
    "GB": "United Kingdom",
    "ZA": "South Africa",
    "BA": "Bosnia and Herzegovina",
}
